version: "3.1"
services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: dao_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mercurial
      - POSTGRES_PASSWORD=mercurial1234
      - POSTGRES_DB=keeper
volumes:
  postgres_data: